version: '2'
services:
    aroundtheworld-app:
        image: aroundtheworld
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://aroundtheworld-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=aroundTheWorld
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aroundtheworld-mongodb:
        extends:
            file: mongodb.yml
            service: aroundtheworld-mongodb
